env:
  node: true
  es2021: true
  browser: true
  cypress/globals: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:cypress/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures: {
    jsx: true
  }
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
  - cypress
  - '@typescript-eslint'
  - eslint-plugin-react
rules: {
  "prettier/prettier": [
    "error",
    {
      "endOfLine": "auto"
    },
    {
      "usePrettierrc": true
    }
  ],
  "cypress/no-force": "warn",
  "cypress/no-pause": "error",
  "cypress/no-async-tests": "error",
  "react/react-in-jsx-scope": "off",
  "cypress/no-unnecessary-waiting": "error",
  "cypress/no-assigning-return-values": "error",
  "cypress/assertion-before-screenshot": "warn"
}
settings: {
  react: {
    version: "detect"
  }
}
