const Head = () => {
	return (
		<>
			<title>Capital Roi</title>
			<meta content='width=device-width, initial-scale=1' name='viewport' />
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.svg' />
		</>
	)
}

export default Head
